 # Copyright (c) Facebook, Inc. and its affiliates.
 # All rights reserved.
 #
 # This source code is licensed under the BSD-style license found in the
 # LICENSE file in the root directory of this source tree.

version: 2.0

jobs:
  build:
    docker:
      - image: flml/flashlight:cuda-base-latest
    steps:
      - checkout
      - run:
          command: |
            mkdir -p build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CUDA
            make && make install
  build-cpu:
    docker:
      - image: flml/flashlight:cpu-base-latest
    steps:
      - checkout
      - run:
          command: |
            export MKLROOT=/opt/intel/mkl && mkdir -p build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU
            make && make install
